"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Cpu, Database, Brain, ShieldAlert, Sparkles, CheckCircle2, RefreshCw, Sliders, ToggleLeft, ToggleRight, Layers, EyeOff } from "lucide-react";
import dynamic from "next/dynamic";
import { useWebGLAvailable } from "../solutions-3d/useWebGLAvailable";

// Dynamically import the 3D Canvas component to reduce initial load times
const Feature3DModel = dynamic(() => import("./Feature3DModel"), {
  ssr: false,
  loading: () => (
    <div className="h-[280px] sm:h-[400px] w-full bg-[#050512]/60 rounded-3xl border border-white/5 flex flex-col items-center justify-center animate-pulse gap-2">
      <div className="h-6 w-6 rounded-full border-2 border-teal-500 border-t-transparent animate-spin" />
      <span className="text-[10px] font-mono text-slate-500 uppercase tracking-widest">
        Initializing WebGL Matrix...
      </span>
    </div>
  ),
});

interface FeatureDetail {
  id: "hermes" | "palace" | "alma" | "clawpatrol";
  name: string;
  tagline: string;
  badge: string;
  icon: any;
  color: string;
  border: string;
  glow: string;
  definition: string;
  highlights: Array<{ title: string; detail: string }>;
  synergy: string;
  benefit: string;
}

const FEATURE_DATA: FeatureDetail[] = [
  {
    id: "hermes",
    name: "Memory OS (Hermes)",
    tagline: "The foundational operating system for unified memory management.",
    badge: "Storage Engine",
    icon: Cpu,
    color: "text-teal-400",
    border: "border-teal-500/20",
    glow: "shadow-[0_0_20px_rgba(20,184,166,0.15)]",
    definition: "Hermes acts as the zero-latency cognitive substrate of DealFlow.AI, unifying data flows into a structured, highly secure hierarchy that feeds the reasoning loop of all autonomous agents.",
    highlights: [
      { title: "4-Tier Active States", detail: "Orchestrates working memory (active dialog context), short-term memory (1-7 day cache), long-term consolidated insights, and immutable cold archives." },
      { title: "Transparent Cryptography", detail: "Provides full field-level AES-256 encryption on rest, decrypting sensitive lead PII dynamically only when verified agent reasoning calls run." },
      { title: "LRU Micro-Cache", detail: "Accelerates retrieval with an in-memory Least Recently Used mechanism, cutting lookup latencies by 60% and optimizing agent processing speeds." },
      { title: "Permission Gates", detail: "Enforces strict agent-level read/write permission scopes, guaranteeing sandbox isolation and data privacy boundaries." }
    ],
    synergy: "Serves as the low-level data engine for MEM Palace to store and retrieve indexes, while capturing and streaming raw dialog variables that feed ALMA's vector database.",
    benefit: "Delivers sub-second agent responsiveness, SOC2 data confidentiality compliance, and zero storage resource leaks."
  },
  {
    id: "palace",
    name: "MEM Palace",
    tagline: "The centralized, organized storage layer built on Hermes.",
    badge: "Knowledge Vault",
    icon: Database,
    color: "text-sky-400",
    border: "border-sky-500/20",
    glow: "shadow-[0_0_20px_rgba(56,189,248,0.15)]",
    definition: "MEM Palace translates raw inputs and volatile event streams generated by Hermes into structured, relational files, mapping lead objections, user behavior tracks, and company rules into searchable categories.",
    highlights: [
      { title: "Structured Relational Maps", detail: "Partitions raw customer transcripts into semantic folders (objections, goals, timelines) for instant agent classification." },
      { title: "Funnel Telemetry Hub", detail: "Aggregates carrier-level SMS delivery webhooks and email click rates directly into a single client contact packet." },
      { title: "Immutable Audit Log", detail: "Maintains tamper-proof records of what data objects were read or written, ensuring robust compliance oversight." }
    ],
    synergy: "Relies on Hermes OS for safe data storage and LRU caching, while presenting ALMA with clean relational records to calculate model embeddings.",
    benefit: "Ensures customer conversation contexts are fully retained over months of engagement, allowing supervisors to review what an agent 'knows' instantly."
  },
  {
    id: "alma",
    name: "ALMA (Agent Learning & Memory)",
    tagline: "The adaptive, continuous agent learning cognitive layer.",
    badge: "Cognitive Processor",
    icon: Brain,
    color: "text-violet-400",
    border: "border-violet-500/20",
    glow: "shadow-[0_0_20px_rgba(129,140,248,0.15)]",
    definition: "ALMA (Agent Learning and Memory Architecture) represents the intelligence loop of DealFlow.AI. It dynamically generates vector embeddings, scores context importance, and grooms database nodes.",
    highlights: [
      { title: "Semantic Vector Search", detail: "Translates conversational data into high-dimensional vector embeddings, matching lead responses with historic context." },
      { title: "Active Promotion Engine", detail: "Evaluates short-term caches and automatically promotes high-importance objection reframes into permanent long-term insights." },
      { title: "Forgetting Grooming", detail: "Offloads low-relevance dialog logs after 30 days to limit prompt pollution and save vector database indexing costs." }
    ],
    synergy: "Monitors the raw data stored in Hermes, structures refined learnings back into MEM Palace relational folders, and generates the context filters that direct agent decision steps.",
    benefit: "Autonomous agents adjust tone and content dynamically based on preceding call notes, achieving maximum target relevance while reducing prompt costs."
  },
  {
    id: "clawpatrol",
    name: "Agent Security Firewall (Clawpatrol)",
    tagline: "Active Zero-Trust protection and policy enforcement.",
    badge: "Security Guard",
    icon: ShieldAlert,
    color: "text-rose-400",
    border: "border-rose-500/20",
    glow: "shadow-[0_0_20px_rgba(244,63,94,0.15)]",
    definition: "Clawpatrol serves as the critical security boundary of our AI agent ecosystem, monitoring all inbound instructions and outbound replies in real time to prevent prompt injection and data leaks.",
    highlights: [
      { title: "15+ Injection Scans", detail: "Scans inbound logs for jailbreaks, prompt override commands, and templated injection patterns, executing automated halts." },
      { title: "Outbound PII Redaction", detail: "Scans agent responses to scrub phone numbers, emails, and base64 credentials before they exit the secure platform boundary." },
      { title: "Behavior Anomaly Scoring", detail: "Maintains a real-time request tracker, blocking user sessions automatically if an anomaly threshold score exceeds 90%." }
    ],
    synergy: "Wraps Hermes OS and ALMA context queries, preventing malicious actors from extracting raw client memory logs or overriding agent system behaviors.",
    benefit: "Protects customer credentials from leaking, guards brand alignment rules, and blocks exploitation vectors by malicious actors."
  }
];

export function FeaturesRedesign() {
  const isWebGL = useWebGLAvailable();
  const [reducedMotion, setReducedMotion] = useState(false);
  
  // Track selected highlight index for each of the 4 features
  const [activeHighlights, setActiveHighlights] = useState<Record<string, number>>({
    hermes: 0,
    palace: 0,
    alma: 0,
    clawpatrol: 0,
  });

  // Load user reduced motion preferences
  useEffect(() => {
    const saved = localStorage.getItem("df_reduce_motion");
    if (saved) {
      setReducedMotion(saved === "true");
      if (saved === "true") {
        document.documentElement.classList.add("reduce-motion-force");
      }
    } else {
      const mq = window.matchMedia("(prefers-reduced-motion: reduce)");
      setReducedMotion(mq.matches);
      if (mq.matches) document.documentElement.classList.add("reduce-motion-force");
    }
  }, []);

  const toggleMotion = () => {
    const nextVal = !reducedMotion;
    setReducedMotion(nextVal);
    localStorage.setItem("df_reduce_motion", String(nextVal));
    if (nextVal) {
      document.documentElement.classList.add("reduce-motion-force");
    } else {
      document.documentElement.classList.remove("reduce-motion-force");
    }
  };

  const handleHighlightSelect = (featureId: string, idx: number) => {
    setActiveHighlights(prev => ({ ...prev, [featureId]: idx }));
  };

  const handleKeyDown = (e: React.KeyboardEvent, featureId: string, idx: number) => {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      handleHighlightSelect(featureId, idx);
    }
  };

  return (
    <div className="space-y-24">
      {/* Redesigned Header Zone with Vestibular Accessibility Toggle */}
      <section className="text-center space-y-6 max-w-4xl mx-auto px-4 pt-10">
        <div className="flex justify-center mb-2">
          <motion.div
            initial={reducedMotion ? {} : { scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="inline-flex items-center gap-2 rounded-full border border-teal-500/30 bg-teal-500/10 px-4 py-1.5 text-xs font-semibold text-teal-300"
          >
            <Sparkles className="h-3.5 w-3.5" />
            <span>Next-Gen Systems</span>
          </motion.div>
        </div>

        <h1 className="font-display text-4xl sm:text-5xl lg:text-7xl font-bold tracking-tight text-white leading-tight">
          Enterprise Agent{" "}
          <span className="bg-gradient-to-r from-teal-400 via-sky-400 to-indigo-400 bg-clip-text text-transparent">
            Architecture.
          </span>
        </h1>

        <p className="text-base sm:text-lg text-slate-400 max-w-2xl mx-auto leading-relaxed">
          Scale your GTM playbooks with four deeply synchronized technical systems managing memory recall, caching, learning, and threat isolation.
        </p>

        {/* Global Motion Control Toggle Button */}
        <div className="flex justify-center pt-2">
          <button
            onClick={toggleMotion}
            className="flex items-center gap-3.5 px-4.5 py-2.5 rounded-2xl border border-white/10 bg-[#090918]/80 backdrop-blur-md hover:bg-[#121228]/85 hover:border-white/20 transition-all font-mono text-xs font-semibold uppercase tracking-wider"
            aria-label={reducedMotion ? "Enable animations" : "Disable animations (Reduce Motion)"}
          >
            <span className="text-slate-400">Reduce Motion</span>
            {reducedMotion ? (
              <ToggleRight className="h-6 w-6 text-teal-400" />
            ) : (
              <ToggleLeft className="h-6 w-6 text-slate-500" />
            )}
          </button>
        </div>
      </section>

      {/* Main Core Showcase alternating grid */}
      <section className="space-y-32">
        {FEATURE_DATA.map((feature, i) => {
          const isAlternate = i % 2 !== 0;
          const IconComponent = feature.icon;
          const currentHighlight = activeHighlights[feature.id] ?? 0;
          const activeDetail = feature.highlights[currentHighlight]?.detail || "";

          return (
            <div
              key={feature.id}
              className={`flex flex-col lg:grid lg:grid-cols-2 gap-10 items-center px-4 max-w-7xl mx-auto scroll-mt-24`}
              id={feature.id}
            >
              {/* WebGL 3D model zone (Alternating sides on desktop) */}
              <div className={`w-full ${isAlternate ? "lg:order-last" : ""}`}>
                {isWebGL ? (
                  <Feature3DModel
                    featureId={feature.id}
                    activeHighlight={currentHighlight}
                    onHighlightClick={(idx) => handleHighlightSelect(feature.id, idx)}
                    reducedMotion={reducedMotion}
                  />
                ) : (
                  // Premium 2D Fallback SVG Model
                  <div className="h-[280px] sm:h-[360px] w-full bg-[#050512]/60 rounded-3xl border border-white/5 flex items-center justify-center p-6 text-center select-none shadow-2xl">
                    <div className="space-y-4">
                      <div className="flex justify-center">
                        <IconComponent className={`h-12 w-12 ${feature.color} animate-pulse`} />
                      </div>
                      <h4 className="text-white font-bold font-display text-lg">{feature.name}</h4>
                      <p className="text-xs text-slate-500 max-w-sm mx-auto leading-relaxed">
                        WebGL is currently disabled or unsupported. Lite 2D layout active for {feature.name}.
                      </p>
                    </div>
                  </div>
                )}
              </div>

              {/* Explanatory Context Copy Zone */}
              <div className="space-y-6 w-full text-left">
                <div className="space-y-3">
                  <div className="flex items-center gap-3">
                    <div className={`p-2.5 rounded-xl border ${feature.border} bg-white/5 ${feature.color}`}>
                      <IconComponent className="h-5 w-5" />
                    </div>
                    <span className={`text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded border ${feature.border} bg-white/5 ${feature.color}`}>
                      {feature.badge}
                    </span>
                  </div>
                  <h2 className="text-2xl sm:text-3xl font-bold font-display text-white leading-tight">
                    {feature.name}
                  </h2>
                  <p className="text-slate-300 font-semibold text-xs leading-normal">
                    {feature.tagline}
                  </p>
                  <p className="text-[11px] text-slate-400 leading-relaxed">
                    {feature.definition}
                  </p>
                </div>

                {/* Highlights Interactive Board */}
                <div className="space-y-3">
                  <h4 className="text-[10px] font-bold uppercase tracking-wider text-slate-500 flex items-center gap-1.5">
                    <Sliders className="h-3.5 w-3.5 text-teal-400" /> Interactive Highlights
                  </h4>
                  <div className="grid grid-cols-2 gap-2">
                    {feature.highlights.map((hl, idx) => {
                      const isSelected = idx === currentHighlight;
                      return (
                        <div
                          key={idx}
                          role="button"
                          tabIndex={0}
                          aria-pressed={isSelected}
                          onClick={() => handleHighlightSelect(feature.id, idx)}
                          onKeyDown={(e) => handleKeyDown(e, feature.id, idx)}
                          className={`p-3 rounded-2xl border transition-all text-left cursor-pointer focus:outline-none focus:ring-1 focus:ring-teal-400/60 ${
                            isSelected
                              ? `bg-white/5 border-white/20 text-white ${feature.glow}`
                              : "border-transparent text-slate-400 hover:bg-white/[0.02]"
                          }`}
                        >
                          <div className="flex items-center gap-2">
                            <CheckCircle2 className={`h-3.5 w-3.5 flex-shrink-0 ${isSelected ? feature.color : "text-slate-600"}`} />
                            <span className="text-xs font-bold leading-none">{hl.title}</span>
                          </div>
                        </div>
                      );
                    })}
                  </div>

                  {/* Contextual Description Detail overlay */}
                  <AnimatePresence mode="wait">
                    <motion.div
                      key={currentHighlight}
                      initial={reducedMotion ? {} : { opacity: 0, y: 5 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={reducedMotion ? {} : { opacity: 0, y: -5 }}
                      className="p-4 rounded-2xl border border-white/5 bg-[#08081a]/60 text-slate-300 text-xs leading-relaxed"
                    >
                      {activeDetail}
                    </motion.div>
                  </AnimatePresence>
                </div>

                {/* System Synergy & Benefits */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 border-t border-white/5 pt-4">
                  <div className="space-y-1.5">
                    <h5 className="text-[9px] font-bold uppercase tracking-wider text-slate-500 flex items-center gap-1">
                      <RefreshCw className="h-3 w-3 text-teal-400" /> Platform Synergy
                    </h5>
                    <p className="text-[11px] text-slate-400 leading-normal">
                      {feature.synergy}
                    </p>
                  </div>
                  <div className="space-y-1.5">
                    <h5 className="text-[9px] font-bold uppercase tracking-wider text-slate-500 flex items-center gap-1">
                      <CheckCircle2 className="h-3 w-3 text-emerald-400" /> User Benefit
                    </h5>
                    <p className="text-[11px] text-slate-400 leading-normal">
                      {feature.benefit}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </section>
    </div>
  );
}
