"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import { 
  Calendar as CalendarIcon, 
  Clock, 
  User, 
  Mail, 
  Building, 
  MessageSquare,
  CheckCircle, 
  ArrowRight, 
  ArrowLeft, 
  AlertCircle, 
  Sparkles,
  Inbox,
  Video,
  Loader2,
  Phone,
  Users,
  Target,
  UserCheck,
  TrendingUp,
  DollarSign,
  Share2,
  Zap,
  ShieldAlert,
  BarChart3,
  Lock
} from "lucide-react";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import type { RevenueAgentProfile } from "@/lib/revenue-agents";
import { formatAnalysisSummaryText } from "@/lib/report-formatter";
import dynamic from "next/dynamic";
import { useCalendlyEventListener } from "react-calendly";
import Link from "next/link";

const DynamicInlineWidget = dynamic(
  () => import("react-calendly").then((mod) => mod.InlineWidget),
  { ssr: false }
);

const GTM_BLUEPRINT = {
  marketSegmentation: {
    title: "1. Target Market Segmentation",
    color: "from-teal-500/10 to-teal-400/5",
    icon: Target,
    insights: [
      { label: "Primary Segment", value: "Mid-Market B2B SaaS ($10M–$100M ARR) experiencing drop-offs in sales pipeline velocity and lead conversion." },
      { label: "Secondary Segment", value: "Enterprise RevOps & Sales Development teams ($100M+ ARR) automating outbound synthesis and lead research workflows." },
      { label: "Tertiary Segment", value: "High-Growth Tech Startups ($1M–$10M ARR) seeking fast GTM playbooks without hiring full-time operations engineers." }
    ]
  },
  customerPersona: {
    title: "2. Customer Persona Overview",
    color: "from-indigo-500/10 to-indigo-400/5",
    icon: UserCheck,
    insights: [
      { label: "VP of Revenue Operations (RevOps)", value: "Focuses on CRM hygiene, tool orchestration (Clay/Salesforce/Apollo), and pipeline analytics. Pain point: Manual pipeline debugging." },
      { label: "VP of Sales / CRO", value: "Focuses on pipeline velocity, quota attainment, and reducing CAC. Pain point: Lead leakage, slow inbound response times." },
      { label: "SDR / Account Executives", value: "Focuses on personalization at scale, instant lead intelligence. Pain point: High manual effort researching contacts." }
    ]
  },
  competitivePositioning: {
    title: "3. Competitive Positioning Analysis",
    color: "from-amber-500/10 to-amber-400/5",
    icon: TrendingUp,
    insights: [
      { label: "Direct Competitors", value: "Static databases (Apollo, ZoomInfo) and conversational chat tools (Intercom, Drift)." },
      { label: "Key Differentiators", value: "Fully autonomous RevOps agents with real-time CRM debugging, automated multi-tool integration, and pre-seeded, interactive playbooks." },
      { label: "Value Proposition", value: "DealFlow.AI bridges data intelligence and execution, reducing manual RevOps work by 80% and lifting pipeline speed by 40%." }
    ]
  },
  pricingStrategy: {
    title: "4. Pricing Strategy Outline",
    color: "from-emerald-500/10 to-emerald-400/5",
    icon: DollarSign,
    insights: [
      { label: "Starter Tier", value: "$1,200/mo — 3 AI Session Agents, 5 pipelines, basic CRM sync, 5,000 automated lead lookups." },
      { label: "RevOps Engine Tier", value: "$3,500/mo — 10 AI Session Agents, unlimited pipelines, advanced multi-tool orchestration, 25,000 lookups." },
      { label: "Enterprise Scale Tier", value: "Custom — Dedicated agent workloads, custom APIs, white-labeled playbooks, infinite scaling, and 24/7 priority SLA support." }
    ]
  },
  distributionChannel: {
    title: "5. Distribution Channel Assessment",
    color: "from-pink-500/10 to-pink-400/5",
    icon: Share2,
    insights: [
      { label: "Direct Inbound (PLG Loop)", value: "Interactive GTM Health Calculator as a viral lead magnet to attract RevOps professionals looking for immediate diagnostics." },
      { label: "Channel Partners", value: "Strategic partnerships with CRM integrators (Salesforce/HubSpot agencies) and modern data tools (Clay certified partners)." },
      { label: "Outbound RevOps Synthesis", value: "Autonomous outreach campaigns generated by DealFlow agents targeting target personas with localized, pre-calculated pipeline leak diagnostics." }
    ]
  },
  marketingSalesAlignment: {
    title: "6. Marketing & Sales Alignment Plan",
    color: "from-blue-500/10 to-blue-400/5",
    icon: Zap,
    insights: [
      { label: "Shared KPI Focus", value: "Lead-to-Booked Consultation Rate and AI-qualified opportunity velocity as primary cross-functional metrics." },
      { label: "RevOps Feedback Loop", value: "Automatic CRM transcription tagging from AI agent interactions is fed into marketing tools to optimize target ads and email scripts." },
      { label: "Lead Handoff SLA", value: "Inbound leads with GTM score < 70 trigger instant AI-agent booking, routing high-value target companies straight to live architects." }
    ]
  },
  riskMitigation: {
    title: "7. Risk Mitigation Framework",
    color: "from-red-500/10 to-red-400/5",
    icon: ShieldAlert,
    insights: [
      { label: "AI Hallucination Risk", value: "Mitigated by strict retrieval guardrails linked to validated vector storage databases with a human-override option." },
      { label: "Data Privacy & Compliance", value: "Zero data retention (ZDR) policies for sensitive customer data, SSL encryption, and GDPR/SOC-2 Type II standards compliance." },
      { label: "API Throttling & Limits", value: "Implemented intelligent rate-limiting queues, localized lead caching, and dual-model redundancy fallbacks." }
    ]
  },
  kpisSuccess: {
    title: "8. Key Performance Indicators (KPIs)",
    color: "from-purple-500/10 to-purple-400/5",
    icon: BarChart3,
    insights: [
      { label: "Launch Velocity", value: "Targeting >28% Lead-to-Booked Strategy Call conversion rate and >95% complete onboarding within 7 days." },
      { label: "Operations Efficiency", value: "Average of >12 minutes interactive session duration, with >65% pipeline blockage diagnosis completed in first week." },
      { label: "Unit Economics", value: "Targeting LTV to CAC ratio of >4:1 in Year 1, with net revenue retention (NRR) exceeding 115%." }
    ]
  }
};

const GTM_TABS = {
  market: {
    label: "Market & Personas",
    sections: ["marketSegmentation", "customerPersona"] as const
  },
  positioning: {
    label: "Positioning & Channels",
    sections: ["competitivePositioning", "distributionChannel"] as const
  },
  pricing: {
    label: "Pricing & Ops",
    sections: ["pricingStrategy", "marketingSalesAlignment"] as const
  },
  risk: {
    label: "Risk & Metrics",
    sections: ["riskMitigation", "kpisSuccess"] as const
  }
};

const getFormattedGtmText = () => {
  return `=== DEALFLOW.AI GO-TO-MARKET (GTM) BLUEPRINT ===

1. TARGET MARKET SEGMENTATION:
- Primary: Mid-Market B2B SaaS ($10M–$100M ARR) experiencing pipeline velocity drop-offs.
- Secondary: Enterprise RevOps & Sales Development ($100M+ ARR) automating lead research.
- Tertiary: High-Growth B2B Tech Startups ($1M–$10M ARR) seeking fast GTM playbooks.

2. CUSTOMER PERSONA OVERVIEW:
- VP of RevOps: Cares about CRM hygiene and automated tool orchestration. Pain: Manual pipeline debugging.
- VP of Sales / CRO: Cares about pipeline velocity and CAC reduction. Pain: Hot lead leakage.
- SDRs / AEs: Cares about personalization at scale. Pain: High manual research effort.

3. COMPETITIVE POSITIONING:
- Competitors: Apollo, ZoomInfo (static data), Intercom, Drift (traditional chatbots).
- Advantage: Fully autonomous agents that run GTM health scores, orchestrate CRM integrations, and execute RevOps workflows.

4. PRICING STRATEGY OUTLINE:
- Starter ($1,200/mo): 3 AI agents, 5 pipelines, CRM sync, 5,000 lead lookups.
- RevOps Engine ($3,500/mo): 10 AI agents, unlimited pipelines, advanced multi-tool integrations, 25,000 lookups.
- Enterprise (Custom): Dedicated agents, custom APIs, priority SLA support.

5. DISTRIBUTION CHANNEL ASSESSMENT:
- PLG Loop: Interactive GTM Health Calculator as a viral lead generator.
- Partners: Salesforce/HubSpot agencies and Clay certified implementation partners.
- Outbound: Autonomous email campaigns using personalized GTM blockages diagnostics.

6. MARKETING & SALES ALIGNMENT:
- Shared KPIs: Lead-to-Booked Consultation rate and pipeline opportunity velocity.
- Feedback Loop: Transcripts of AI agent sessions auto-tagged in CRM to optimize ad copy.
- SLA: Hot leads (GTM score < 70) trigger immediate live-architect routing.

7. RISK MITIGATION FRAMEWORK:
- AI Hallucination: Protected by tight vector retrieval guardrails and human-takeover fallbacks.
- Privacy/Compliance: Zero Data Retention (ZDR) mode, SSL encryption, SOC-2 Type II standards.
- Throttling: Local lead caching and query queue batching.

8. KEY PERFORMANCE INDICATORS (KPIs):
- Launch Velocity: >28% Lead-to-Booked Consultation rate.
- Operations: Average session >12 minutes, >65% blockages diagnosed.
- Economics: CAC-to-LTV ratio >4x in Year 1, Net Retention Rate (NRR) >115%.`;
};

const DEFAULT_GTM_OUTLINE = `=== GO-TO-MARKET (GTM) ANALYSIS OUTLINE ===

1. TARGET MARKET SEGMENTATION:
- Primary Segment: [e.g., Mid-Market B2B SaaS, $10M–$100M ARR]
- Secondary Segment: [e.g., Enterprise RevOps Teams, $100M+ ARR]

2. CUSTOMER PERSONA DEFINITION:
- Target Personas: [e.g., VP of RevOps, CRO, VP of Sales]
- Core Pain Points: [e.g., Manual pipeline debugging, lead leakage]

3. COMPETITIVE LANDSCAPE ASSESSMENT:
- Direct Competitors: [e.g., ZoomInfo, Apollo, legacy chat tools]
- Key Differentiators: [e.g., Autonomous multi-tool execution, real-time CRM diagnostics]

4. VALUE PROPOSITION ARTICULATION:
- Core Value Prop: [e.g., Reduce manual RevOps overhead by 80% and accelerate pipeline velocity by 40%]

5. DISTRIBUTION CHANNEL STRATEGY:
- Channels: [e.g., PLG loop with GTM health checks, CRM channel partners, direct outreach]

6. PRICING MODEL FRAMEWORK:
- Pricing Structure: [e.g., Value-based per active AI agent session and data credits]

7. MARKETING CAMPAIGN ROADMAP:
- Key Campaigns: [e.g., Viral GTM calculator tools, pipeline leakage whitepapers]

8. SALES ENABLEMENT PLAN:
- Enablement Assets: [e.g., Automated CRM case study decks, ROI calculators, playbooks]

9. RISK MITIGATION STRATEGY:
- Core Risks & Mitigations: [e.g., AI hallucination guardrails, GDPR/SOC-2 ZDR compliance]

10. SUCCESS METRIC TRACKING FRAMEWORK:
- Success Metrics / KPIs: [e.g., Lead-to-Booked Consultation rate, CAC:LTV, active session duration]`;

type Props = {
  name: string;
  email: string;
  companyName?: string;
  contactPhone?: string;
  leadId?: string;
  analysisId?: string;
  skipAiAgent?: boolean;
  forcedMeetingType?: "cal" | "calendly";
  challengeTags?: string[];
};

export function BookingWidget({ 
  name: initialName, 
  email: initialEmail, 
  companyName: initialCompanyName,
  contactPhone: initialPhone = "",
  leadId: initialLeadId, 
  analysisId, 
  skipAiAgent,
  forcedMeetingType,
  challengeTags = [],
}: Props) {
  const router = useRouter();
  
  // Form and Step States
  const [step, setStep] = useState<1 | 2 | 3 | 4>(1);
  const [bookingMode, setBookingMode] = useState<"ai" | "live" | null>(null);
  const [showAgentPicker, setShowAgentPicker] = useState(false);
  const [agents, setAgents] = useState<RevenueAgentProfile[]>([]);
  const [selectedAgentKeys, setSelectedAgentKeys] = useState<string[]>([]);
  const [autoAssignAgent, setAutoAssignAgent] = useState(true);
  const [loadingAgents, setLoadingAgents] = useState(false);
  const [voiceConfirmationQueued, setVoiceConfirmationQueued] = useState(false);
  const [calendlyLoading, setCalendlyLoading] = useState(true);
  const [password, setPassword] = useState("");
  const [assignedAgent, setAssignedAgent] = useState<any | null>(null);

  // Setup Calendly event listener to validate and register successful bookings
  useCalendlyEventListener({
    onProfilePageViewed: () => setCalendlyLoading(false),
    onEventTypeViewed: () => setCalendlyLoading(false),
    onEventScheduled: (e) => {
      console.log("Calendly appointment scheduled:", e.data.payload);
      void handleCalendlyBookingSuccess();
    }
  });

  // Backup safety net to clear Calendly loading spinner in case event listeners don't fire
  useEffect(() => {
    if (step === 2 && forcedMeetingType === "calendly") {
      setCalendlyLoading(true);
      const timer = setTimeout(() => {
        setCalendlyLoading(false);
      }, 2500);
      return () => clearTimeout(timer);
    }
  }, [step, forcedMeetingType]);
  
  // Scheduler States
  const [selectedDate, setSelectedDate] = useState<string>("");
  const [selectedTime, setSelectedTime] = useState<string>("");
  
  // User Details Form States
  const [formData, setFormData] = useState({
    name: initialName || "",
    email: initialEmail || "",
    company: initialCompanyName || "",
    phone: initialPhone || "",
    message: DEFAULT_GTM_OUTLINE
  });
  const [formErrors, setFormErrors] = useState<Record<string, string>>({});
  const [isGtmDashboardOpen, setIsGtmDashboardOpen] = useState(true);
  const [gtmActiveTab, setGtmActiveTab] = useState<"market" | "positioning" | "pricing" | "risk">("market");
  const [hasUserModified, setHasUserModified] = useState(false);
  
  // System States
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [createdCallId, setCreatedCallId] = useState<string>("");
  const [createdMeetUrl, setCreatedMeetUrl] = useState<string>("");
  const [analysisSummary, setAnalysisSummary] = useState<string>("");

  // Fetch analysis summary for pre-filling meeting notes or backend reference
  useEffect(() => {
    if (!analysisId) return;

    async function fetchAndFormatAnalysis() {
      try {
        const res = await fetch(`/api/analysis/${analysisId}`);
        const data = await res.json();
        if (data.success) {
          const summary = formatAnalysisSummaryText(data);
          setAnalysisSummary(summary);
          setFormData(prev => {
            if (hasUserModified) return prev;
            return {
              ...prev,
              message: (prev.message === "" || prev.message === DEFAULT_GTM_OUTLINE)
                ? `Hi, I would like to discuss our GTM Health Score of ${data.healthScore}/100 and pipeline insights.`
                : prev.message
            };
          });
        }
      } catch (err) {
        console.error("Error fetching analysis summary:", err);
      }
    }

    fetchAndFormatAnalysis();
  }, [analysisId, hasUserModified]);

  // Sync initial props
  useEffect(() => {
    setFormData(prev => ({
      ...prev,
      name: prev.name || initialName,
      email: prev.email || initialEmail,
      company: prev.company || initialCompanyName || "",
      phone: prev.phone || initialPhone || "",
    }));
  }, [initialName, initialEmail, initialCompanyName, initialPhone]);

  const loadAgents = useCallback(async () => {
    setLoadingAgents(true);
    try {
      const res = await fetch("/api/agents");
      const data = await res.json();
      if (data.success && Array.isArray(data.agents)) {
        setAgents(data.agents);
      }
    } catch (err) {
      console.error("Failed to load revenue agents:", err);
    } finally {
      setLoadingAgents(false);
    }
  }, []);

  const toggleAgentSelection = (key: string) => {
    setSelectedAgentKeys(prev =>
      prev.includes(key) ? prev.filter(k => k !== key) : [...prev, key]
    );
  };

  // Standard Guests list matching the backend
  const defaultGuests = useMemo(() => [
    "praneethburada@gmail.com",
    "praneeth@growstack.ai",
    "teambproject864@gmail.com",
    "kunal@growstack.ai",
  ], []);

  // Generate local upcoming business days (excluding weekends)
  const businessDays = useMemo(() => {
    const days = [];
    let current = new Date();
    
    // Add upcoming 6 business days
    while (days.length < 6) {
      current.setDate(current.getDate() + 1);
      const dayOfWeek = current.getDay();
      if (dayOfWeek !== 0 && dayOfWeek !== 6) { // Exclude Sat/Sun
        const dayStr = current.toLocaleDateString("en-US", {
          weekday: "short",
          month: "short",
          day: "numeric"
        });
        const isoStr = current.toISOString().split("T")[0];
        days.push({ label: dayStr, value: isoStr });
      }
    }
    return days;
  }, []);

  // Set default selected date
  useEffect(() => {
    if (businessDays.length > 0 && !selectedDate) {
      setSelectedDate(businessDays[0].value);
    }
  }, [businessDays, selectedDate]);

  // Standard available time slots
  const availableSlots = useMemo(() => [
    { time: "09:30 AM", label: "Morning" },
    { time: "10:30 AM", label: "Morning" },
    { time: "11:15 AM", label: "Morning" },
    { time: "02:00 PM", label: "Afternoon" },
    { time: "03:30 PM", label: "Afternoon" },
    { time: "04:45 PM", label: "Evening" }
  ], []);

  // Active timezone detection
  const timeZoneName = useMemo(() => {
    try {
      return Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC";
    } catch {
      return "UTC";
    }
  }, []);

  // Form Validation
  const validateForm = useCallback(() => {
    const errors: Record<string, string> = {};
    if (!formData.name.trim()) errors.name = "Name is required";
    if (!formData.email.trim()) {
      errors.email = "Email is required";
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email.trim())) {
      errors.email = "Invalid email address";
    }
    if (!formData.company.trim()) errors.company = "Company name is required";
    if (!formData.phone.trim()) {
      errors.phone = "Phone number is required";
    } else if (!/^\+?[1-9]\d{1,14}$/.test(formData.phone.replace(/[\s()+-]/g, ""))) {
      errors.phone = "Invalid phone number format";
    }
    
    setFormErrors(errors);
    return Object.keys(errors).length === 0;
  }, [formData]);

  // Step 1 CTA Handler: Instant AI Call Session
  const handleStartAiAgent = async () => {
    setLoading(true);
    setErrorMsg(null);
    try {
      let resolvedLeadId = initialLeadId;
      
      // Save lead first if not exists
      if (!resolvedLeadId) {
        const resLead = await fetch("/api/leads/save", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            companyName: formData.company || "Prospect",
            contactName: formData.name || "Guest",
            contactEmail: formData.email,
            contactPhone: formData.phone || "000-000-0000",
            source: "booking_widget_ai_direct",
          }),
        });
        const leadJson = await resLead.json();
        if (resLead.ok && leadJson.leadId) {
          resolvedLeadId = String(leadJson.leadId);
        } else {
          throw new Error(leadJson.error || "Lead profile creation failed");
        }
      }

      // Create Immediate Call
      const resCall = await fetch("/api/calls/immediate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          leadId: resolvedLeadId,
          analysisId: analysisId || "",
          personaKey: "praneeth_assist",
          preferredAgentKeys: selectedAgentKeys,
          autoAssign: autoAssignAgent,
        })
      });
      
      const callData = await resCall.json();
      if (!resCall.ok) {
        throw new Error(callData.error || "No immediate AI consultation slots available. Please schedule a strategy call.");
      }

      if (callData.success && callData.callId) {
        if (skipAiAgent) {
          router.push("/");
        } else {
          router.push(`/meeting-agent/live?callId=${callData.callId}`);
        }
      } else {
        throw new Error("Failed to boot AI session agent");
      }
    } catch (err: any) {
      console.error("AI booking failure:", err);
      setErrorMsg(err.message || "An error occurred starting the AI session.");
    } finally {
      setLoading(false);
    }
  };

  const handleStartAiAgentOnboarding = async () => {
    // 1. Validate Form Inputs
    const errors: Record<string, string> = {};
    if (!formData.name.trim()) errors.name = "Name is required";
    if (!formData.email.trim()) {
      errors.email = "Email is required";
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email.trim())) {
      errors.email = "Invalid email address";
    }
    if (!formData.company.trim()) errors.company = "Company name is required";
    if (!formData.phone.trim()) {
      errors.phone = "Phone number is required";
    } else if (!/^\+?[1-9]\d{1,14}$/.test(formData.phone.replace(/[\s()+-]/g, ""))) {
      errors.phone = "Invalid phone number format";
    }
    if (!password || password.length < 6) {
      errors.password = "Password must be at least 6 characters";
    }
    if (Object.keys(errors).length > 0) {
      setFormErrors(errors);
      return;
    }

    setLoading(true);
    setErrorMsg(null);
    try {
      let resolvedLeadId = initialLeadId;
      
      // A. Create/Save Lead in database if not present
      if (!resolvedLeadId) {
        const resLead = await fetch("/api/leads/save", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            companyName: formData.company,
            contactName: formData.name,
            contactEmail: formData.email,
            contactPhone: formData.phone,
            source: "booking_widget_ai_onboard",
          }),
        });
        const leadJson = await resLead.json();
        if (resLead.ok && leadJson.leadId) {
          resolvedLeadId = String(leadJson.leadId);
        } else {
          throw new Error(leadJson.error || "Failed to create lead profile.");
        }
      }

      // B. Resolve Agent Key
      const agentKey = autoAssignAgent ? (agents[0]?.key || "praneeth") : (selectedAgentKeys[0] || "praneeth");

      // C. Save Agent Assignment
      const resAssign = await fetch("/api/agent-assignments", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          leadId: resolvedLeadId,
          agentKey: agentKey,
        })
      });
      const assignData = await resAssign.json();
      if (!resAssign.ok || !assignData.success) {
        throw new Error(assignData.error || "Failed to assign AI agent.");
      }
      setAssignedAgent(assignData.assignment);

      // D. Register Portal Credentials
      const resCreds = await fetch("/api/customer-credentials", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          leadId: resolvedLeadId,
          email: formData.email,
          password: password,
        })
      });
      const credsData = await resCreds.json();
      if (!resCreds.ok || !credsData.success) {
        throw new Error(credsData.error || "Failed to create customer credentials.");
      }

      // E. Create Immediate Call in background (pre-boots session)
      try {
        const resCall = await fetch("/api/calls/immediate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            leadId: resolvedLeadId,
            analysisId: analysisId || "",
            personaKey: "praneeth_assist",
            preferredAgentKeys: [agentKey],
            autoAssign: false,
          })
        });
        const callData = await resCall.json();
        if (resCall.ok && callData.success && callData.callId) {
          setCreatedCallId(callData.callId);
        }
      } catch (err) {
        console.warn("Failed to pre-create immediate call session in background:", err);
      }

      // Transition to Success Step
      setStep(4);
    } catch (err: any) {
      console.error("AI Onboarding error:", err);
      setErrorMsg(err.message || "Failed to complete onboarding. Try again.");
    } finally {
      setLoading(false);
    }
  };

  // Step 3 Handler: Submit live schedule request
  const handleBookMeeting = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!validateForm()) return;
    
    setLoading(true);
    setErrorMsg(null);
    try {
      let resolvedLeadId = initialLeadId;
      
      // 1. Create Lead in database if not present
      if (!resolvedLeadId) {
        const resLead = await fetch("/api/leads/save", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            companyName: formData.company,
            contactName: formData.name,
            contactEmail: formData.email,
            contactPhone: formData.phone,
            source: "booking_widget_scheduler",
          }),
        });
        const leadJson = await resLead.json();
        if (resLead.ok && leadJson.leadId) {
          resolvedLeadId = String(leadJson.leadId);
        } else {
          throw new Error(leadJson.error || "Failed to create lead details.");
        }
      }

      // Combine date and time to ISO String
      // Split "09:30 AM" into hours and minutes
      const [timePart, modifier] = selectedTime.split(" ");
      let [hours, minutes] = timePart.split(":").map(Number);
      if (modifier === "PM" && hours < 12) hours += 12;
      if (modifier === "AM" && hours === 12) hours = 0;
      
      const scheduledDate = new Date(selectedDate);
      scheduledDate.setHours(hours, minutes, 0, 0);

      // 2. Call backend create endpoint
      const resCall = await fetch("/api/calls/create", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          leadId: resolvedLeadId,
          analysisId: analysisId || "",
          meetingUrl: "", // Generate Meet URL automatically
          scheduledAt: scheduledDate.toISOString(),
          guests: defaultGuests
        })
      });

      const callData = await resCall.json();
      if (!resCall.ok) {
        throw new Error(callData.error || "Failed to schedule strategy call.");
      }

      if (callData.success) {
        setCreatedCallId(callData.callId);
        setVoiceConfirmationQueued(true);
        // Wait 1.5 seconds to query the new meeting URL details if generated
        setTimeout(async () => {
          try {
            const getCallRes = await fetch(`/api/calls/${callData.callId}`);
            const fullCall = await getCallRes.json();
            if (fullCall?.meetingUrl) {
              setCreatedMeetUrl(fullCall.meetingUrl);
            }
          } catch {
            setCreatedMeetUrl("https://meet.google.com/gtm-ops-dfai");
          }
        }, 1500);
        
        setStep(4);
      } else {
        throw new Error("Unable to save scheduled booking.");
      }
    } catch (err: any) {
      console.error("Booking error:", err);
      setErrorMsg(err.message || "Failed to establish booking. Try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleCalendlyBookingSuccess = async () => {
    setLoading(true);
    setErrorMsg(null);
    try {
      let resolvedLeadId = initialLeadId;
      
      // 1. Create Lead in database if not present
      if (!resolvedLeadId) {
        const resLead = await fetch("/api/leads/save", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            companyName: formData.company || "Acme Corp",
            contactName: formData.name || "Calendly User",
            contactEmail: formData.email || "calendly-user@example.com",
            contactPhone: formData.phone || "",
            source: "booking_widget_calendly",
          }),
        });
        const leadJson = await resLead.json();
        if (resLead.ok && leadJson.leadId) {
          resolvedLeadId = String(leadJson.leadId);
        } else {
          throw new Error(leadJson.error || "Failed to create lead details.");
        }
      }

      // 2. Call backend create endpoint
      const resCall = await fetch("/api/calls/create", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          leadId: resolvedLeadId,
          analysisId: analysisId || "",
          meetingUrl: process.env.NEXT_PUBLIC_CALENDLY_URL || "https://calendly.com/praneethburada/30min",
          scheduledAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(), // Proxy 24h slots
          guests: defaultGuests
        })
      });

      const callData = await resCall.json();
      if (!resCall.ok) {
        throw new Error(callData.error || "Failed to register Calendly booking.");
      }

      if (callData.success) {
        setCreatedCallId(callData.callId);
        setVoiceConfirmationQueued(true);
        setCreatedMeetUrl(process.env.NEXT_PUBLIC_CALENDLY_URL || "https://calendly.com/praneethburada/30min");
        
        // Transition to Step 4 success screen
        setStep(4);
      } else {
        throw new Error("Unable to save scheduled booking.");
      }
    } catch (err: any) {
      console.error("Calendly booking save error:", err);
      setErrorMsg(err.message || "Failed to register your Calendly slot. Please contact support.");
    } finally {
      setLoading(false);
    }
  };

  // Human friendly scheduled date preview
  const friendlyScheduledDate = useMemo(() => {
    if (!selectedDate || !selectedTime) return "";
    try {
      const [timePart, modifier] = selectedTime.split(" ");
      let [hours, minutes] = timePart.split(":").map(Number);
      if (modifier === "PM" && hours < 12) hours += 12;
      if (modifier === "AM" && hours === 12) hours = 0;
      
      const date = new Date(selectedDate);
      date.setHours(hours, minutes, 0, 0);
      return date.toLocaleDateString("en-US", {
        weekday: "long",
        month: "long",
        day: "numeric",
        hour: "numeric",
        minute: "2-digit"
      }) + ` (${timeZoneName})`;
    } catch {
      return `${selectedDate} at ${selectedTime}`;
    }
  }, [selectedDate, selectedTime, timeZoneName]);

  return (
    <div className="w-full bg-[#0A0F1E]/60 border border-white/10 rounded-3xl overflow-hidden backdrop-blur-xl shadow-2xl relative">
      
      {/* Progress Header */}
      <div className="border-b border-white/5 bg-white/[0.02] px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="h-2 w-2 rounded-full bg-teal-500 animate-pulse" />
          <span className="text-xs font-bold text-slate-300 uppercase tracking-widest">
            Pipeline Architect Booking System
          </span>
        </div>
        
        {/* Step Indicators */}
        <div className="flex items-center gap-2">
          {[1, 2, 3, 4].map((i) => (
            <div 
              key={i} 
              className={`h-1.5 rounded-full transition-all duration-300 ${
                step === i 
                  ? "w-6 bg-teal-400" 
                  : step > i 
                    ? "w-2 bg-emerald-500" 
                    : "w-2 bg-white/10"
              }`} 
            />
          ))}
        </div>
      </div>

      {/* Main Form Display */}
      <div className="p-8 sm:p-10">
        
        {/* Global Error Banner */}
        {errorMsg && (
          <motion.div 
            initial={{ opacity: 0, y: -10 }} 
            animate={{ opacity: 1, y: 0 }}
            className="mb-6 p-4 rounded-xl border border-red-500/20 bg-red-500/10 text-red-300 flex items-start gap-3"
          >
            <AlertCircle className="h-5 w-5 shrink-0 mt-0.5" />
            <div className="text-sm font-medium">{errorMsg}</div>
          </motion.div>
        )}

        <AnimatePresence mode="wait">
          
          {/* STEP 1: Dual Choice CTAs */}
          {step === 1 && (
            <motion.div
              key="step1"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              transition={{ duration: 0.3 }}
              className="space-y-8"
            >
              <div className="text-center space-y-2">
                <h3 className="text-2xl font-semibold text-white tracking-tight sm:text-3xl font-display">
                  Choose Consultation Vector
                </h3>
                <p className="text-slate-400 max-w-xl mx-auto text-sm sm:text-base">
                  Analyze and implement your custom AI solutions matrix instantly, or reserve a slot with our revenue operations team.
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4">
                
                {/* AI Instant Agent Choice */}
                <div 
                  onClick={() => { setBookingMode("ai"); }}
                  className={`group relative rounded-2xl border p-6 flex flex-col justify-between cursor-pointer transition-all duration-300 h-[260px] ${
                    bookingMode === "ai" 
                      ? "border-teal-500 bg-teal-500/[0.06] shadow-[0_0_30px_rgba(20,184,166,0.15)]" 
                      : "border-white/10 bg-white/[0.02] hover:border-white/20 hover:bg-white/[0.04]"
                  }`}
                >
                  <div className="absolute inset-0 bg-gradient-to-br from-teal-500/5 to-transparent rounded-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                  
                  <div className="space-y-4 relative z-10">
                    <div className="h-12 w-12 rounded-xl bg-teal-500/10 border border-teal-500/25 flex items-center justify-center text-teal-400 group-hover:scale-110 transition-transform duration-300 shadow-[0_0_15px_rgba(20,184,166,0.2)]">
                      <Sparkles className="h-6 w-6" />
                    </div>
                    <div>
                      <h4 className="text-lg font-bold text-white flex items-center gap-2">
                        Consult AI Revenue Agent
                        <span className="text-[10px] font-extrabold uppercase bg-teal-400/20 text-teal-300 px-2 py-0.5 rounded border border-teal-400/30">
                          Active
                        </span>
                      </h4>
                      <p className="text-xs text-slate-400 mt-2 leading-relaxed">
                        Instantly boot a live operations cockpit. Run through interactive playbooks, debug pipeline blockages, and translate analysis readouts in real-time.
                      </p>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 text-xs font-semibold text-teal-400 mt-4 relative z-10">
                    <span>Initiate Immediate Intake Session</span>
                    <ArrowRight className="h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" />
                  </div>
                </div>

                {/* Live Strategy Booking Choice */}
                <div 
                  onClick={() => { setBookingMode("live"); }}
                  className={`group relative rounded-2xl border p-6 flex flex-col justify-between cursor-pointer transition-all duration-300 h-[260px] ${
                    bookingMode === "live" 
                      ? "border-indigo-500 bg-indigo-500/[0.06] shadow-[0_0_30px_rgba(99,102,241,0.15)]" 
                      : "border-white/10 bg-white/[0.02] hover:border-white/20 hover:bg-white/[0.04]"
                  }`}
                >
                  <div className="absolute inset-0 bg-gradient-to-br from-indigo-500/5 to-transparent rounded-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                  
                  <div className="space-y-4 relative z-10">
                    <div className="h-12 w-12 rounded-xl bg-indigo-500/10 border border-indigo-500/25 flex items-center justify-center text-indigo-400 group-hover:scale-110 transition-transform duration-300 shadow-[0_0_15px_rgba(99,102,241,0.2)]">
                      <CalendarIcon className="h-6 w-6" />
                    </div>
                    <div>
                      <h4 className="text-lg font-bold text-white flex items-center gap-2">
                        Schedule GTM Strategy Call
                      </h4>
                      <p className="text-xs text-slate-400 mt-2 leading-relaxed">
                        Reserve a 30-minute dedicated work session. Run a diagnostic sync, explore specific tool integrations (Salesforce/Apollo/Clay), and structure your operations roadmap.
                      </p>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 text-xs font-semibold text-indigo-400 mt-4 relative z-10">
                    <span>Lock in Strategy Time Slot</span>
                    <ArrowRight className="h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" />
                  </div>
                </div>

              </div>

              {showAgentPicker && bookingMode === "ai" && (
                <div className="rounded-2xl border border-teal-500/25 bg-teal-500/[0.04] p-6 space-y-5">
                  <div className="flex items-center gap-2">
                    <Users className="h-5 w-5 text-teal-400" />
                    <h4 className="text-sm font-bold text-white uppercase tracking-wider">
                      Select AI Revenue Agent
                    </h4>
                  </div>

                  {loadingAgents ? (
                    <div className="flex items-center gap-2 text-sm text-slate-400">
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Loading available agents...
                    </div>
                  ) : (
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      {agents.map((agent) => (
                        <label
                          key={agent.key}
                          className={`flex items-start gap-3 rounded-xl border p-4 cursor-pointer transition-all ${
                            selectedAgentKeys.includes(agent.key)
                              ? "border-teal-500 bg-teal-500/10"
                              : "border-white/10 bg-black/20 hover:border-white/20"
                          } ${!agent.available ? "opacity-60" : ""}`}
                        >
                          <Checkbox
                            checked={selectedAgentKeys.includes(agent.key)}
                            onCheckedChange={() => toggleAgentSelection(agent.key)}
                            disabled={autoAssignAgent}
                            className="mt-0.5"
                          />
                          <div className="space-y-1 min-w-0">
                            <p className="text-sm font-bold text-white">{agent.fullName}</p>
                            <p className="text-xs text-slate-400">{agent.role}</p>
                            <p className="text-[10px] text-slate-500">
                              {agent.available ? "Available" : "At capacity"} · {agent.activeSessions} active session
                              {agent.activeSessions === 1 ? "" : "s"}
                            </p>
                          </div>
                        </label>
                      ))}
                    </div>
                  )}

                  <div className="flex items-start gap-3 rounded-xl border border-white/10 bg-black/30 p-4">
                    <Checkbox
                      id="autoAssignAgent"
                      checked={autoAssignAgent}
                      onCheckedChange={(checked) => {
                        const enabled = checked === true;
                        setAutoAssignAgent(enabled);
                        if (enabled) setSelectedAgentKeys([]);
                      }}
                    />
                    <div>
                      <Label htmlFor="autoAssignAgent" className="text-sm font-semibold text-white cursor-pointer">
                        Automatic agent assignment
                      </Label>
                      <p className="text-xs text-slate-400 mt-1">
                        Assigns the best-fit agent based on workload, expertise alignment, and current availability.
                      </p>
                    </div>
                  </div>
                </div>
              )}

              <div className="flex justify-between items-center pt-6">
                {showAgentPicker && bookingMode === "ai" ? (
                  <button
                    type="button"
                    onClick={() => setShowAgentPicker(false)}
                    className="text-xs text-slate-400 hover:text-white"
                  >
                    <ArrowLeft className="inline h-3.5 w-3.5 mr-1" />
                    Back to options
                  </button>
                ) : (
                  <span />
                )}
                <button
                  type="button"
                  disabled={!bookingMode || loading}
                  onClick={() => {
                    if (bookingMode === "ai") {
                      if (!showAgentPicker) {
                        setShowAgentPicker(true);
                        void loadAgents();
                      } else {
                        setStep(2);
                      }
                    } else {
                      setStep(2);
                    }
                  }}
                  className="inline-flex items-center gap-2 rounded-xl bg-teal-500 px-6 py-3.5 text-sm font-semibold text-black transition-all hover:bg-teal-400 hover:scale-105 active:scale-95 disabled:opacity-40 disabled:pointer-events-none shadow-[0_0_20px_rgba(20,184,166,0.3)] duration-300"
                >
                  {loading ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin text-black" />
                      Allocating Agent...
                    </>
                  ) : bookingMode === "ai" && !showAgentPicker ? (
                    <>
                      Choose Your Agent
                      <ArrowRight className="h-4 w-4" />
                    </>
                  ) : (
                    <>
                      {bookingMode === "ai" ? "Start Consultation" : "Confirm Selection"}
                      <ArrowRight className="h-4 w-4" />
                    </>
                  )}
                </button>
              </div>
            </motion.div>
          )}

          {step === 2 && (
            <motion.div
              key="step2"
              initial={{ opacity: 0, x: 50 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -50 }}
              transition={{ duration: 0.3 }}
              className="space-y-6"
            >
              {bookingMode === "ai" ? (
                <>
                  <div className="flex items-center justify-between border-b border-white/5 pb-4 mb-4">
                    <div>
                      <h3 className="text-xl font-semibold text-white font-display">
                        Create Your Customer Account & Onboard
                      </h3>
                      <p className="text-xs text-slate-400 mt-1">
                        Configure your credentials to access the Customer Portal and launch your AI Agent.
                      </p>
                    </div>
                    <button 
                      onClick={() => setStep(1)} 
                      className="inline-flex items-center gap-1.5 text-xs text-slate-400 hover:text-white transition-colors focus:outline-none"
                    >
                      <ArrowLeft className="h-3.5 w-3.5" /> Back
                    </button>
                  </div>

                  <form 
                    onSubmit={async (e) => {
                      e.preventDefault();
                      void handleStartAiAgentOnboarding();
                    }} 
                    className="space-y-5"
                  >
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                      {/* Name field */}
                      <div className="space-y-2">
                        <Label htmlFor="ai-name" className="text-xs font-semibold text-slate-300 flex items-center gap-2">
                          <User className="h-3.5 w-3.5 text-teal-400" />
                          Contact Name <span className="text-red-400">*</span>
                        </Label>
                        <input
                          id="ai-name"
                          type="text"
                          placeholder="Praneeth Burada"
                          value={formData.name}
                          onChange={(e) => {
                            setFormData({ ...formData, name: e.target.value });
                            if (formErrors.name) setFormErrors({ ...formErrors, name: "" });
                          }}
                          className={`w-full bg-black/40 border rounded-xl px-4 py-3 text-sm text-white placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-teal-500 transition-all ${
                            formErrors.name ? "border-red-500/50" : "border-white/10 focus:border-teal-500"
                          }`}
                        />
                        {formErrors.name && (
                          <span className="text-[11px] text-red-400 flex items-center gap-1 mt-1">
                            <AlertCircle className="h-3 w-3" /> {formErrors.name}
                          </span>
                        )}
                      </div>

                      {/* Company field */}
                      <div className="space-y-2">
                        <Label htmlFor="ai-company" className="text-xs font-semibold text-slate-300 flex items-center gap-2">
                          <Building className="h-3.5 w-3.5 text-teal-400" />
                          Company Name <span className="text-red-400">*</span>
                        </Label>
                        <input
                          id="ai-company"
                          type="text"
                          placeholder="Growstack AI"
                          value={formData.company}
                          onChange={(e) => {
                            setFormData({ ...formData, company: e.target.value });
                            if (formErrors.company) setFormErrors({ ...formErrors, company: "" });
                          }}
                          className={`w-full bg-black/40 border rounded-xl px-4 py-3 text-sm text-white placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-teal-500 transition-all ${
                            formErrors.company ? "border-red-500/50" : "border-white/10 focus:border-teal-500"
                          }`}
                        />
                        {formErrors.company && (
                          <span className="text-[11px] text-red-400 flex items-center gap-1 mt-1">
                            <AlertCircle className="h-3 w-3" /> {formErrors.company}
                          </span>
                        )}
                      </div>

                      {/* Phone field */}
                      <div className="space-y-2 md:col-span-2">
                        <Label htmlFor="ai-phone" className="text-xs font-semibold text-slate-300 flex items-center gap-2">
                          <Phone className="h-3.5 w-3.5 text-teal-400" />
                          Contact Phone <span className="text-red-400">*</span>
                        </Label>
                        <input
                          id="ai-phone"
                          type="tel"
                          placeholder="+1 (555) 123-4567"
                          value={formData.phone}
                          onChange={(e) => {
                            setFormData({ ...formData, phone: e.target.value });
                            if (formErrors.phone) setFormErrors({ ...formErrors, phone: "" });
                          }}
                          className={`w-full bg-black/40 border rounded-xl px-4 py-3 text-sm text-white placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-teal-500 transition-all ${
                            formErrors.phone ? "border-red-500/50" : "border-white/10 focus:border-teal-500"
                          }`}
                        />
                        {formErrors.phone && (
                          <span className="text-[11px] text-red-400 flex items-center gap-1 mt-1">
                            <AlertCircle className="h-3 w-3" /> {formErrors.phone}
                          </span>
                        )}
                      </div>

                      {/* Portal Email field */}
                      <div className="space-y-2">
                        <Label htmlFor="ai-email" className="text-xs font-semibold text-slate-300 flex items-center gap-2">
                          <Mail className="h-3.5 w-3.5 text-teal-400" />
                          Portal Login Email <span className="text-red-400">*</span>
                        </Label>
                        <input
                          id="ai-email"
                          type="email"
                          placeholder="you@company.com"
                          value={formData.email}
                          onChange={(e) => {
                            setFormData({ ...formData, email: e.target.value });
                            if (formErrors.email) setFormErrors({ ...formErrors, email: "" });
                          }}
                          className={`w-full bg-black/40 border rounded-xl px-4 py-3 text-sm text-white placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-teal-500 transition-all ${
                            formErrors.email ? "border-red-500/50" : "border-white/10 focus:border-teal-500"
                          }`}
                        />
                        {formErrors.email && (
                          <span className="text-[11px] text-red-400 flex items-center gap-1 mt-1">
                            <AlertCircle className="h-3 w-3" /> {formErrors.email}
                          </span>
                        )}
                      </div>

                      {/* Portal Password field */}
                      <div className="space-y-2">
                        <Label htmlFor="ai-password" className="text-xs font-semibold text-slate-300 flex items-center gap-2">
                          <Lock className="h-3.5 w-3.5 text-teal-400" />
                          Portal Password <span className="text-red-400">*</span>
                        </Label>
                        <input
                          id="ai-password"
                          type="password"
                          placeholder="Create secure password"
                          value={password}
                          onChange={(e) => {
                            setPassword(e.target.value);
                            if (formErrors.password) setFormErrors({ ...formErrors, password: "" });
                          }}
                          className={`w-full bg-black/40 border rounded-xl px-4 py-3 text-sm text-white placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-teal-500 transition-all ${
                            formErrors.password ? "border-red-500/50" : "border-white/10 focus:border-teal-500"
                          }`}
                        />
                        {formErrors.password && (
                          <span className="text-[11px] text-red-400 flex items-center gap-1 mt-1">
                            <AlertCircle className="h-3 w-3" /> {formErrors.password}
                          </span>
                        )}
                      </div>
                    </div>

                    <div className="flex justify-between items-center pt-6 border-t border-white/5 mt-6">
                      <span className="text-xs text-slate-400">
                        {autoAssignAgent ? "Auto-assigning best fit AI Agent" : `Selected ${selectedAgentKeys.length} Agent(s)`}
                      </span>
                      <button
                        type="submit"
                        disabled={loading}
                        className="inline-flex items-center gap-2 rounded-xl bg-teal-500 px-6 py-3.5 text-sm font-semibold text-black transition-all hover:bg-teal-400 hover:scale-105 active:scale-95 disabled:opacity-40 disabled:pointer-events-none shadow-[0_0_20px_rgba(20,184,166,0.3)] duration-300"
                      >
                        {loading ? (
                          <>
                            <Loader2 className="h-4 w-4 animate-spin text-black" />
                            Provisioning Portal...
                          </>
                        ) : (
                          <>
                            Complete Setup & Launch
                            <ArrowRight className="h-4 w-4" />
                          </>
                        )}
                      </button>
                    </div>
                  </form>
                </>
              ) : forcedMeetingType === "calendly" ? (
                <div className="rounded-2xl border border-white/10 bg-[#0A0F1E]/50 overflow-hidden min-h-[660px] relative shadow-inner">
                  {/* Accessibility support announcement */}
                  <span className="sr-only">Calendly Scheduling Widget. Use keyboard tab to navigate scheduling calendar below.</span>
                  
                  {/* Loading State during Calendly initialization */}
                  {calendlyLoading && (
                    <div className="absolute inset-0 flex flex-col items-center justify-center bg-[#0A0F1E]/80 backdrop-blur-sm z-20 space-y-4">
                      <Loader2 className="h-8 w-8 animate-spin text-teal-400" />
                      <div className="text-center space-y-1">
                        <p className="text-sm font-bold text-white uppercase tracking-wider animate-pulse">
                          Loading Revenue Architect Scheduler...
                        </p>
                        <p className="text-xs text-slate-400">
                          Fetching live available slots from Calendly.
                        </p>
                      </div>
                    </div>
                  )}
                  
                  <div style={{ height: "650px", width: "100%" }}>
                    <DynamicInlineWidget
                      url={process.env.NEXT_PUBLIC_CALENDLY_URL || "https://calendly.com/praneethburada/30min"}
                      prefill={{
                        email: formData.email,
                        name: formData.name,
                      }}
                      styles={{
                        height: "100%",
                        width: "100%"
                      }}
                    />
                  </div>
                </div>
              ) : (
                <>
                  <div className="grid grid-cols-1 lg:grid-cols-[1.3fr_1fr] gap-8">
                    
                    {/* Date Grid */}
                    <div className="space-y-4">
                      <span className="text-xs font-semibold uppercase tracking-wider text-slate-400 flex items-center gap-2">
                        <CalendarIcon className="h-3.5 w-3.5 text-teal-400" />
                        Select Business Day
                      </span>
                      <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                        {businessDays.map((day) => (
                          <div
                            key={day.value}
                            onClick={() => { setSelectedDate(day.value); setSelectedTime(""); }}
                            className={`p-4 rounded-xl border text-center cursor-pointer transition-all duration-200 ${
                              selectedDate === day.value
                                ? "border-teal-500 bg-teal-500/10 text-white shadow-[0_0_15px_rgba(20,184,166,0.15)]"
                                : "border-white/10 bg-white/[0.01] text-slate-300 hover:border-white/20 hover:bg-white/[0.03]"
                            }`}
                          >
                            <span className="block text-xs text-slate-400 mb-1">
                              {day.label.split(",")[0]}
                            </span>
                            <span className="text-sm font-bold block">
                              {day.label.split(",")[1]}
                            </span>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Slots Grid */}
                    <div className="space-y-4">
                      <span className="text-xs font-semibold uppercase tracking-wider text-slate-400 flex items-center gap-2">
                        <Clock className="h-3.5 w-3.5 text-teal-400" />
                        Available Slots ({timeZoneName})
                      </span>
                      
                      <div className="grid grid-cols-2 gap-3">
                        {availableSlots.map((slot) => (
                          <div
                            key={slot.time}
                            onClick={() => setSelectedTime(slot.time)}
                            className={`p-3 rounded-xl border text-center cursor-pointer transition-all duration-200 ${
                              selectedTime === slot.time
                                ? "border-teal-500 bg-teal-500/10 text-white shadow-[0_0_15px_rgba(20,184,166,0.15)]"
                                : "border-white/10 bg-white/[0.01] text-slate-300 hover:border-white/20 hover:bg-white/[0.03]"
                            }`}
                          >
                            <span className="text-xs block text-slate-500 mb-0.5">{slot.label}</span>
                            <span className="text-sm font-semibold">{slot.time}</span>
                          </div>
                        ))}
                      </div>
                    </div>

                  </div>

                  {/* Navigation Action Buttons */}
                  <div className="flex justify-between items-center pt-6 border-t border-white/5 mt-6">
                    <span className="text-xs text-slate-400">
                      {selectedDate && selectedTime ? (
                        <span className="text-teal-400 font-medium">
                          Selected: {selectedDate} at {selectedTime}
                        </span>
                      ) : (
                        "Please select a date and time slot"
                      )}
                    </span>
                    <button
                      type="button"
                      disabled={!selectedDate || !selectedTime}
                      onClick={() => setStep(3)}
                      className="inline-flex items-center gap-2 rounded-xl bg-teal-500 px-6 py-3.5 text-sm font-semibold text-black transition-all hover:bg-teal-400 hover:scale-105 active:scale-95 disabled:opacity-40 disabled:pointer-events-none shadow-[0_0_20px_rgba(20,184,166,0.3)] duration-300"
                    >
                      Continue to Details
                      <ArrowRight className="h-4 w-4" />
                    </button>
                  </div>
                </>
              )}
            </motion.div>
          )}

          {/* STEP 3: Form Collection Details with Validation */}
          {step === 3 && (
            <motion.div
              key="step3"
              initial={{ opacity: 0, x: 50 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -50 }}
              transition={{ duration: 0.3 }}
              className="space-y-6"
            >
              <div className="flex items-center justify-between border-b border-white/5 pb-4 mb-4">
                <div>
                  <h3 className="text-xl font-semibold text-white font-display">Enter Meeting Details</h3>
                  <p className="text-xs text-slate-400 mt-1">Pre-filling details using your intake context session</p>
                </div>
                <button 
                  onClick={() => setStep(2)} 
                  className="inline-flex items-center gap-1.5 text-xs text-slate-400 hover:text-white transition-colors"
                >
                  <ArrowLeft className="h-3.5 w-3.5" /> Back to Slots
                </button>
              </div>

              <form onSubmit={handleBookMeeting} className="space-y-5">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                  {/* Phone field */}
                  <div className="space-y-2 md:col-span-2">
                    <label className="text-xs font-semibold text-slate-300 flex items-center gap-2">
                      <Phone className="h-3.5 w-3.5 text-teal-400" />
                      Contact Phone <span className="text-red-400">*</span>
                      <span className="text-slate-500 font-normal">(for automated confirmation call)</span>
                    </label>
                    <input
                      type="tel"
                      placeholder="+1 (555) 123-4567"
                      value={formData.phone}
                      onChange={(e) => {
                        setFormData({ ...formData, phone: e.target.value });
                        if (formErrors.phone) setFormErrors({ ...formErrors, phone: "" });
                      }}
                      className={`w-full bg-black/40 border rounded-xl px-4 py-3 text-sm text-white placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-teal-500 transition-all ${
                        formErrors.phone ? "border-red-500/50" : "border-white/10 focus:border-teal-500"
                      }`}
                    />
                    {formErrors.phone && (
                      <span className="text-[11px] text-red-400 flex items-center gap-1 mt-1">
                        <AlertCircle className="h-3 w-3" /> {formErrors.phone}
                      </span>
                    )}
                  </div>

                  {/* Name field */}
                  <div className="space-y-2">
                    <label className="text-xs font-semibold text-slate-300 flex items-center gap-2">
                      <User className="h-3.5 w-3.5 text-teal-400" />
                      Contact Name <span className="text-red-400">*</span>
                    </label>
                    <div className="relative">
                      <input
                        type="text"
                        placeholder="Praneeth Burada"
                        value={formData.name}
                        onChange={(e) => {
                          setFormData({ ...formData, name: e.target.value });
                          if (formErrors.name) setFormErrors({ ...formErrors, name: "" });
                        }}
                        className={`w-full bg-black/40 border rounded-xl px-4 py-3 text-sm text-white placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-teal-500 transition-all ${
                          formErrors.name ? "border-red-500/50 focus:ring-red-500" : "border-white/10 focus:border-teal-500"
                        }`}
                      />
                    </div>
                    {formErrors.name && (
                      <span className="text-[11px] text-red-400 flex items-center gap-1 mt-1">
                        <AlertCircle className="h-3 w-3" /> {formErrors.name}
                      </span>
                    )}
                  </div>

                  {/* Email field */}
                  <div className="space-y-2">
                    <label className="text-xs font-semibold text-slate-300 flex items-center gap-2">
                      <Mail className="h-3.5 w-3.5 text-teal-400" />
                      Contact Email <span className="text-red-400">*</span>
                    </label>
                    <input
                      type="email"
                      placeholder="praneeth@growstack.ai"
                      value={formData.email}
                      onChange={(e) => {
                        setFormData({ ...formData, email: e.target.value });
                        if (formErrors.email) setFormErrors({ ...formErrors, email: "" });
                      }}
                      className={`w-full bg-black/40 border rounded-xl px-4 py-3 text-sm text-white placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-teal-500 transition-all ${
                        formErrors.email ? "border-red-500/50 focus:ring-red-500" : "border-white/10 focus:border-teal-500"
                      }`}
                    />
                    {formErrors.email && (
                      <span className="text-[11px] text-red-400 flex items-center gap-1 mt-1">
                        <AlertCircle className="h-3 w-3" /> {formErrors.email}
                      </span>
                    )}
                  </div>

                </div>

                <div className="grid grid-cols-1 gap-5">
                  
                  {/* Company field */}
                  <div className="space-y-2">
                    <label className="text-xs font-semibold text-slate-300 flex items-center gap-2">
                      <Building className="h-3.5 w-3.5 text-teal-400" />
                      Company Name <span className="text-red-400">*</span>
                    </label>
                    <input
                      type="text"
                      placeholder="Growstack AI"
                      value={formData.company}
                      onChange={(e) => {
                        setFormData({ ...formData, company: e.target.value });
                        if (formErrors.company) setFormErrors({ ...formErrors, company: "" });
                      }}
                      className={`w-full bg-black/40 border rounded-xl px-4 py-3 text-sm text-white placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-teal-500 transition-all ${
                        formErrors.company ? "border-red-500/50 focus:ring-red-500" : "border-white/10 focus:border-teal-500"
                      }`}
                    />
                    {formErrors.company && (
                      <span className="text-[11px] text-red-400 flex items-center gap-1 mt-1">
                        <AlertCircle className="h-3 w-3" /> {formErrors.company}
                      </span>
                    )}
                  </div>

                  {/* Message field with GTM Blueprint Display */}
                  <div className="space-y-3">
                    <div className="flex items-center justify-between">
                      <label className="text-xs font-semibold text-slate-300 flex items-center gap-2">
                        <MessageSquare className="h-3.5 w-3.5 text-teal-400" />
                        Special Instructions / Focus Topics
                      </label>
                      <button
                        type="button"
                        onClick={() => setIsGtmDashboardOpen(!isGtmDashboardOpen)}
                        className="text-xs text-teal-400 hover:text-teal-300 font-semibold transition-colors flex items-center gap-1.5 focus:outline-none bg-teal-500/5 hover:bg-teal-500/10 border border-teal-500/20 px-2.5 py-1 rounded-lg"
                      >
                        <Sparkles className="h-3 w-3 animate-pulse" />
                        {isGtmDashboardOpen ? "Hide GTM Blueprint" : "View GTM Launch Blueprint"}
                      </button>
                    </div>
                    <textarea
                      rows={6}
                      placeholder="Share specific tools, domains or stages you want to target during our operations session..."
                      value={formData.message}
                      onChange={(e) => {
                        setFormData({ ...formData, message: e.target.value });
                        setHasUserModified(true);
                      }}
                      className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-sm text-white placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-teal-500 transition-all focus:border-teal-500"
                    />

                    {isGtmDashboardOpen && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: "auto" }}
                        exit={{ opacity: 0, height: 0 }}
                        className="rounded-2xl border border-teal-500/20 bg-slate-900/60 backdrop-blur-xl p-5 mt-4 space-y-4 overflow-hidden relative shadow-[0_4px_30px_rgba(20,184,166,0.05)]"
                      >
                        {/* Glow effect in background */}
                        <div className="absolute top-0 right-0 w-32 h-32 bg-teal-500/5 rounded-full blur-3xl pointer-events-none" />
                        <div className="absolute bottom-0 left-0 w-32 h-32 bg-indigo-500/5 rounded-full blur-3xl pointer-events-none" />

                        {/* Header info */}
                        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 pb-3 border-b border-white/5 relative z-10">
                          <div className="space-y-0.5">
                            <div className="flex items-center gap-2 flex-wrap">
                              <Sparkles className="h-3.5 w-3.5 text-teal-400" />
                              <h4 className="text-xs font-bold text-white uppercase tracking-wider">
                                DealFlow AI — Revenue Strategy Blueprint
                              </h4>
                              <span className="text-[8px] font-extrabold uppercase bg-teal-400/20 text-teal-300 px-1.5 py-0.5 rounded border border-teal-400/20">
                                Engine Output
                              </span>
                            </div>
                            <p className="text-[10px] text-slate-400">
                              Autonomous GTM diagnostic synthesis generated for your strategy workshop.
                            </p>
                          </div>

                          <button
                            type="button"
                            onClick={() => {
                              setFormData(prev => ({
                                ...prev,
                                message: getFormattedGtmText()
                              }));
                              setHasUserModified(true);
                            }}
                            className="shrink-0 self-start sm:self-center text-[10px] font-bold bg-teal-500 hover:bg-teal-400 text-black px-2.5 py-1.5 rounded-lg transition-all duration-300 hover:scale-105 active:scale-95 shadow-[0_0_15px_rgba(20,184,166,0.2)] flex items-center gap-1 focus:outline-none"
                          >
                            <Inbox className="h-3 w-3 text-black" />
                            Pre-fill Booking Notes
                          </button>
                        </div>

                        {/* Tab Selectors */}
                        <div className="flex flex-wrap gap-1.5 relative z-10">
                          {(Object.keys(GTM_TABS) as Array<keyof typeof GTM_TABS>).map((tabKey) => {
                            const tab = GTM_TABS[tabKey];
                            const isActive = gtmActiveTab === tabKey;
                            
                            // Get icons inline based on tabKey
                            let TabIcon = Target;
                            if (tabKey === "positioning") TabIcon = TrendingUp;
                            if (tabKey === "pricing") TabIcon = DollarSign;
                            if (tabKey === "risk") TabIcon = ShieldAlert;

                            return (
                              <button
                                key={tabKey}
                                type="button"
                                onClick={() => setGtmActiveTab(tabKey)}
                                className={`px-2.5 py-1.5 rounded-lg text-[10px] font-bold transition-all duration-200 flex items-center gap-1.5 border focus:outline-none ${
                                  isActive
                                    ? "border-teal-500/40 bg-teal-500/10 text-white shadow-[0_0_10px_rgba(20,184,166,0.1)]"
                                    : "border-white/5 bg-white/[0.01] text-slate-400 hover:text-white hover:border-white/10 hover:bg-white/[0.03]"
                                }`}
                              >
                                <TabIcon className="h-3 w-3" />
                                {tab.label}
                              </button>
                            );
                          })}
                        </div>

                        {/* Active Tab Content Grid */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 relative z-10">
                          {GTM_TABS[gtmActiveTab].sections.map((sectionKey) => {
                            const section = GTM_BLUEPRINT[sectionKey];
                            const IconComponent = section.icon;

                            return (
                              <div
                                key={sectionKey}
                                className={`rounded-xl border border-white/5 bg-gradient-to-br ${section.color} p-4 space-y-3 hover:border-white/10 transition-all duration-300`}
                              >
                                <div className="flex items-center gap-2 pb-2 border-b border-white/5">
                                  <div className="p-1.5 rounded-md bg-white/5 border border-white/10 text-teal-400">
                                    <IconComponent className="h-3.5 w-3.5" />
                                  </div>
                                  <h5 className="text-[10px] font-bold text-slate-200 uppercase tracking-wider">
                                    {section.title}
                                  </h5>
                                </div>

                                <div className="space-y-2.5">
                                  {section.insights.map((insight, idx) => (
                                    <div key={idx} className="space-y-0.5">
                                      <span className="text-[8px] uppercase font-extrabold text-teal-300 tracking-wider block">
                                        {insight.label}
                                      </span>
                                      <p className="text-[11px] text-slate-300 leading-relaxed">
                                        {insight.value}
                                      </p>
                                    </div>
                                  ))}
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </motion.div>
                    )}
                  </div>

                </div>

                {/* Submit Panel */}
                <div className="flex justify-between items-center pt-6 border-t border-white/5 mt-6">
                  <div className="text-xs text-slate-400 flex items-center gap-1">
                    <Clock className="h-3 w-3 text-slate-500" />
                    <span>Selected: {selectedTime} on {selectedDate}</span>
                  </div>
                  
                  <button
                    type="submit"
                    disabled={loading}
                    className="inline-flex items-center gap-2 rounded-xl bg-teal-500 px-6 py-3.5 text-sm font-semibold text-black transition-all hover:bg-teal-400 hover:scale-105 active:scale-95 disabled:opacity-40 disabled:pointer-events-none shadow-[0_0_20px_rgba(20,184,166,0.3)] duration-300"
                  >
                    {loading ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin text-black" />
                        Scheduling Call...
                      </>
                    ) : (
                      <>
                        Book Strategy Call
                        <CheckCircle className="h-4 w-4" />
                      </>
                    )}
                  </button>
                </div>
              </form>
            </motion.div>
          )}

          {/* STEP 4: Success Confirmation & HTML Email Notification Preview */}
          {step === 4 && (
            <motion.div
              key="step4"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.4, ease: "easeOut" }}
              className="space-y-8"
            >
              {bookingMode === "ai" ? (
                <div className="space-y-8">
                  {/* Success Badge */}
                  <div className="text-center space-y-4">
                    <div className="mx-auto h-16 w-16 rounded-full bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400 shadow-[0_0_30px_rgba(16,185,129,0.2)]">
                      <CheckCircle className="h-8 w-8 animate-pulse" />
                    </div>
                    <div className="space-y-1">
                      <h3 className="text-2xl font-semibold text-white tracking-tight sm:text-3xl font-display">
                        AI Agent Onboarded & Assigned!
                      </h3>
                      <p className="text-sm text-slate-400">
                        Your customer portal is configured and your AI revenue agent is ready to execute your GTM playbook.
                      </p>
                    </div>
                  </div>

                  {/* Agent Card Details */}
                  {assignedAgent && (
                    <div className="bg-white/[0.02] border border-white/5 rounded-2xl p-6 flex items-center gap-4 text-left max-w-lg mx-auto">
                      <div className="w-16 h-16 rounded-full bg-gradient-to-br from-teal-500 to-purple-600 flex items-center justify-center text-white font-bold text-2xl shadow-[0_0_15px_rgba(20,184,166,0.2)]">
                        {assignedAgent.agentName.charAt(0)}
                      </div>
                      <div className="flex-1">
                        <span className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-teal-500/10 text-teal-300 text-xs font-semibold uppercase tracking-wider border border-teal-500/20">
                          Active Agent
                        </span>
                        <h4 className="text-xl font-bold text-white mt-1">{assignedAgent.agentName}</h4>
                        <p className="text-xs text-slate-400 mt-0.5">Status: Assigned & Synchronized</p>
                      </div>
                    </div>
                  )}

                  {/* Portal Instructions & Actions */}
                  <div className="space-y-4 max-w-md mx-auto pt-4">
                    <div className="flex flex-col sm:flex-row gap-4 justify-center">
                      <Link 
                        href="/portal/customer"
                        className="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-500 px-6 py-3.5 text-sm font-semibold text-black transition-all hover:bg-teal-400 hover:scale-105 active:scale-95 shadow-[0_0_20px_rgba(20,184,166,0.3)] duration-300 w-full sm:w-auto"
                      >
                        Access Customer Portal
                        <ArrowRight className="h-4 w-4" />
                      </Link>

                      {createdCallId && (
                        <button
                          type="button"
                          onClick={() => router.push(`/meeting-agent/live?callId=${createdCallId}`)}
                          className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-800 border border-slate-700 px-6 py-3.5 text-sm font-semibold text-white transition-all hover:bg-slate-700 hover:scale-105 active:scale-95 duration-300 w-full sm:w-auto"
                        >
                          <Video className="h-4 w-4 text-teal-400" />
                          Launch Live Call Session
                        </button>
                      )}
                    </div>
                    
                    <p className="text-[11px] text-slate-500 text-center italic">
                      Note: You can log into your Customer Portal at any time using your registered email: {formData.email}.
                    </p>
                  </div>
                </div>
              ) : (
                <>
                  {/* Success Badge */}
                  <div className="text-center space-y-4">
                    <div className="mx-auto h-16 w-16 rounded-full bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400 shadow-[0_0_30px_rgba(16,185,129,0.2)]">
                      <CheckCircle className="h-8 w-8 animate-pulse" />
                    </div>
                    <div className="space-y-1">
                      <h3 className="text-2xl font-semibold text-white tracking-tight sm:text-3xl font-display">
                        Strategy Session Confirmed!
                      </h3>
                      <p className="text-sm text-slate-400">
                        We&apos;ve registered your GTM analysis mapping and generated your workspace invite.
                        {voiceConfirmationQueued && formData.phone && (
                          <span className="block mt-2 text-teal-400/90">
                            An automated confirmation call to {formData.phone} is being placed with your meeting details.
                          </span>
                        )}
                      </p>
                    </div>
                  </div>

                  {/* Event details card */}
                  <div className="bg-white/[0.02] border border-white/5 rounded-2xl p-6 grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-3">
                      <div className="text-xs uppercase tracking-wider text-slate-500 font-bold">Scheduled Time</div>
                      <div className="flex items-start gap-2.5">
                        <CalendarIcon className="h-4 w-4 text-teal-400 shrink-0 mt-0.5" />
                        <span className="text-sm font-semibold text-white">{friendlyScheduledDate}</span>
                      </div>
                    </div>

                    <div className="space-y-3">
                      <div className="text-xs uppercase tracking-wider text-slate-500 font-bold">Workspace Video URL</div>
                      <div className="flex items-start gap-2.5">
                        <Video className="h-4 w-4 text-indigo-400 shrink-0 mt-0.5" />
                        <a 
                          href={createdMeetUrl || "https://meet.google.com/gtm-ops-dfai"} 
                          target="_blank" 
                          rel="noopener noreferrer" 
                          className="text-sm font-semibold text-indigo-400 hover:text-indigo-300 underline break-all"
                        >
                          {createdMeetUrl ? createdMeetUrl : "https://meet.google.com/gtm-ops-dfai"}
                        </a>
                      </div>
                    </div>
                  </div>

                  {/* PREMIUM FEATURE: Automated Confirmation Email Presentation */}
                  <div className="space-y-3">
                    <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-400">
                      <Inbox className="h-4 w-4 text-teal-400" />
                      <span>Automated Confirmation Email Dispatched</span>
                    </div>

                    <div className="relative rounded-2xl border border-white/10 bg-[#0A0F1E]/80 overflow-hidden shadow-2xl p-6">
                      {/* Glassmorphic Email Layout */}
                      <div className="flex items-center gap-3 border-b border-white/5 pb-4 mb-4 text-xs">
                        <span className="h-2 w-2 rounded-full bg-emerald-500" />
                        <div className="text-slate-400 font-medium">
                          To: <span className="text-slate-200">{formData.email}</span>
                        </div>
                        <div className="ml-auto text-slate-500">Just Now</div>
                      </div>

                      <div className="space-y-4 text-sm text-slate-300">
                        <div className="font-bold text-white text-base">
                          Subject: GTM Strategy Booking Confirmation — {formData.company}
                        </div>
                        
                        <p>Hi {formData.name.split(" ")[0]},</p>
                        <p>
                          Your dedicated 30-minute GTM Strategy Call with DealFlow.AI has been booked! We are looking forward to helping you optimize your revenue engine.
                        </p>

                        <div className="p-4 rounded-xl bg-white/[0.03] border border-white/5 space-y-2 text-xs text-slate-400">
                          <div><strong className="text-slate-200">Date/Time:</strong> {friendlyScheduledDate}</div>
                          <div><strong className="text-slate-200">Video Link:</strong> <a href={createdMeetUrl || "https://meet.google.com/gtm-ops-dfai"} className="text-indigo-400 underline">{createdMeetUrl || "https://meet.google.com/gtm-ops-dfai"}</a></div>
                          <div><strong className="text-slate-200">Invited Operation Architects:</strong> {defaultGuests.slice(0, 2).join(", ")}</div>
                        </div>

                        <p className="text-xs text-slate-500 italic">
                          Note: An agenda has been pre-seeded containing your GTM Health score and primary RevOps bottlenecks.
                        </p>
                      </div>
                    </div>
                  </div>

                  {/* Confirmation Action Button */}
                  <div className="flex justify-center pt-4">
                    <button
                      type="button"
                      onClick={() => {
                        // Pushes back to Home cockpit or lead status
                        router.push("/");
                      }}
                      className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-teal-500 to-emerald-500 px-8 py-3.5 text-sm font-semibold text-black transition-all hover:scale-105 active:scale-95 shadow-[0_0_30px_rgba(20,184,166,0.3)] duration-300"
                    >
                      Access Revenue Cockpit
                      <ArrowRight className="h-4 w-4" />
                    </button>
                  </div>
                </>
              )}

            </motion.div>
          )}

        </AnimatePresence>

      </div>
    </div>
  );
}
